- title: CarKunda
  desc: Nepal's comprehensive car info platform with specs, prices & comparisons.
  platforms: [web]
  image_style: default
  url: https://carkunda.com
  release_url: /product-launches/
  latest_release: true
- title: ClipKunda
  desc: Privacy-first clipboard manager with local AI.
  platforms: [macos]
  image_style: default
  url: /clipkunda/
  release_url: /product-launches/
- title: Sour.Chat
  desc: Modern chat platform for AI-driven conversations.
  platforms: [web]
  image_style: default
  url: https://sour.chat
- title: LogicLand
  desc: Educational games for kids to learn math & logic.
  platforms: [ios, android]
  image_style: graph
  url: /logicland/
  release_url: /product-launches/
