- title: ClipKunda
  desc: Privacy-first clipboard manager with local AI and rich docs.
  image_style: default
  url: /clipkunda/
  release_url: /releases/clipkunda/
  latest_release: true
- title: Sour.Chat
  desc: Modern chat platform for AI-driven conversations.
  image_style: default
  url: https://sour.chat
